=== ro-kl/XML-Parser/src/fahrzeugdatenbank.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
DTD von newWaveRacer.xml

Roman Kluth

<!ELEMENT elementname(inhaltsmodell)>
-->

<!ELEMENT fahrzeugdatenbank (fahrzeug)*>
<!ELEMENT fahrzeug (ausstattungsliste, motor, anmerkung, produktionsdatum)>
<!ATTLIST fahrzeug
	vorbesitzer CDATA #IMPLIED
	hersteller CDATA #IMPLIED
	modellbezeichnung CDATA #REQUIRED
	seriennummer CDATA #REQUIRED
        farbe CDATA #REQUIRED
 >
<!ELEMENT produktionsdatum EMPTY>
<!ATTLIST produktionsdatum
	tag CDATA #REQUIRED
	monat CDATA #REQUIRED
        jahr CDATA #REQUIRED
 >
<!ELEMENT anmerkung (#PCDATA)>

<!ELEMENT motor EMPTY>
<!ATTLIST motor
	zylinderanzahl CDATA #REQUIRED
	brennstoffart CDATA #REQUIRED
        hubraum CDATA #REQUIRED  
 >
<!ELEMENT ausstattungsliste (ausstattungsoption)*>
<!ELEMENT ausstattungsoption EMPTY>
<!ATTLIST ausstattungsoption
	bezeichnung CDATA #REQUIRED
	anzahl CDATA #REQUIRED
        einzelpreis CDATA #REQUIRED
 >

=== ro-kl/XML-Parser/src/fahrzeugdatenbank.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE fahrzeugdatenbank SYSTEM "fahrzeugdatenbank.dtd">
<fahrzeugdatenbank>
    <fahrzeug hersteller="" vorbesitzer="" modellbezeichnung="R8"
        seriennummer="123789" farbe="Rot">
        <produktionsdatum tag="01" monat="06" jahr="2012"/>
        <anmerkung>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, pretium quis, sem.</anmerkung>
        <motor zylinderanzahl="12" brennstoffart="Diesel" hubraum="5800"/>
        <ausstattungsliste>
            <ausstattungsoption bezeichnung="Ledersitze" anzahl="4" einzelpreis="1200"/>
            <ausstattungsoption bezeichnung="20 Zoll Felgen" anzahl="4" einzelpreis="600"/>
        </ausstattungsliste>
    </fahrzeug>
    <fahrzeug hersteller="" vorbesitzer="" modellbezeichnung="Prius"
        seriennummer="654987" farbe="Blau">
        <produktionsdatum tag="20" monat="12" jahr="2006"/>
        <anmerkung>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, pretium quis, sem.</anmerkung>
        <motor zylinderanzahl="6" brennstoffart="Benzin" hubraum="3500"/>
        <ausstattungsliste>
            <ausstattungsoption bezeichnung="Winterreifen" anzahl="5" einzelpreis="50"/>
        </ausstattungsliste>
    </fahrzeug>
    <fahrzeug hersteller="" vorbesitzer="2" modellbezeichnung="Golf"
        seriennummer="21436587" farbe="Schwarz">
        <produktionsdatum tag="08" monat="01" jahr="1964"/>
        <anmerkung>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, pretium quis, sem.</anmerkung>
        <motor zylinderanzahl="6" brennstoffart="Benzin" hubraum="1200"/>
        <ausstattungsliste>
            <ausstattungsoption bezeichnung="Felgen" anzahl="4" einzelpreis="60"/>
            <ausstattungsoption bezeichnung="Winterreifen" anzahl="4" einzelpreis="45"/>
        </ausstattungsliste>
    </fahrzeug>
</fahrzeugdatenbank>

=== ro-kl/XML-Parser/src/newWaveRacer.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE fahrzeugdatenbank SYSTEM "fahrzeugdatenbank.dtd">
<fahrzeugdatenbank>
<fahrzeug vorbesitzer="2" hersteller="veryoldmobil" modellbezeichnung="Schrotti-2000"
seriennummer="1749421" farbe="schwarz" >
<produktionsdatum tag="01" monat="04" jahr="1988"/>
<anmerkung >Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
Aenean commodo ligula eget dolor. Aenean massa. Cum sociis
natoque penatibus et magnis dis parturient montes, nascetur
ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, pretium quis, sem.
</anmerkung>
<motor zylinderanzahl="12" brennstoffart="benzin" hubraum="4629" />
<ausstattungsliste>
<ausstattungsoption bezeichnung="18 Zoll Alufelge" anzahl="4" einzelpreis="381"/>
<ausstattungsoption bezeichnung="Sektkuehler" anzahl="1" einzelpreis="1423"/>
<ausstattungsoption bezeichnung="Lenkrad aus Wurzelholz" anzahl="1"
einzelpreis="501" />
</ausstattungsliste>
</fahrzeug>
</fahrzeugdatenbank>
